cmake_minimum_required(VERSION 3.30)
project(nx3d LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

include(cmake/Nexilis.cmake)
add_subdirectory(server)
option(NX3D_BUILD_CLIENT "Build the Vulkan game client" ON)
if(NX3D_BUILD_CLIENT)
    add_subdirectory(client)
endif()
include(CTest)
if(BUILD_TESTING)
    add_subdirectory(tests)
endif()
